apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  type: LoadBalancer
  loadBalancerIP: 48.217.193.70  # Specify the desired public IP address
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: swiggy-app
