version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2
  kubernetes: circleci/kubernetes@0.11.0

jobs:
  deploy_k8s:
    docker:
      - image: cimg/openjdk:17.0.11-browsers
    steps:
      - checkout
      - azure-cli/install
      - run:
          name: List files for debugging
          command: ls -la
      - run:
          name: Azure CLI Login
          command: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      - run:
          name: Get AKS Credentials
          command: |
            az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME
      - kubernetes/install-kubectl
      - run:
          name: Apply Kubernetes Deployment
          command: |
            cd kubernetes
            kubectl apply -f deployment.yaml
      - run:
          name: Apply Kubernetes service
          command: |
            cd kubernetes
            kubectl apply -f service.yaml

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy_k8s:
          filters:
            branches:
              only: k8_deploy
