version: 2.1
# Orbs define
orbs:
  azure-cli: circleci/azure-cli@1.2.2
  terraform: circleci/terraform@3.1

jobs:
  deploy_infrastructure:
    docker:
      - image: cimg/openjdk:17.0.11-browsers
    steps:
      - checkout
      - azure-cli/install
      - terraform/install
      - run:
          name: List files for debugging
          command: ls -la
      - run:
          name: Azure CLI Login
          command: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      - run:
          name: Change to Terraform Directory
          command: cd terraform
      - run:
          name: List files in Terraform Directory
          command: ls -la
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy_infrastructure
