version: 2.1
# Orbs define
orbs:
  azure-cli: circleci/azure-cli@1.2.2
  terraform: circleci/terraform@3.1

jobs:
  deploy_infrastructure:
    docker:
      - image: cimg/openjdk:17.0.11-browsers
    steps:
      - checkout
      - terraform/install

      - run:
          name: Terraform Init
          command: |
            cd terraform
            terraform init
      - run:
          name: Terraform Plan
          command: |
            cd terraform
            terraform plan -var="subscription_id=${ARM_SUBSCRIPTION_ID}" -var="client_id=${ARM_CLIENT_ID}" -var="client_secret=${ARM_CLIENT_SECRET}" -var="tenant_id=${ARM_TENANT_ID}"
      - run:
          name: Terraform apply
          command: |
            cd terraform
            terraform apply \
              -var="subscription_id=${ARM_SUBSCRIPTION_ID}" \
              -var="client_id=${ARM_CLIENT_ID}" \
              -var="client_secret=${ARM_CLIENT_SECRET}" \
              -var="tenant_id=${ARM_TENANT_ID}" \
              -auto-approve

      - run:
          name: Trigger k8_deploy Pipeline
          command: |
            curl -X POST "https://circleci.com/api/v2/gh/deathtkr/firsadit_repo/pipeline" \
            -H "Circle-Token: ${CIRCLECI_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{"branch": "k8_deploy"}'


workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy_infrastructure
