version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout

      - run:
          name: Clear nuget
          command: dotnet nuget locals all --clear
      - run:
          name: Restore dependencies
          command: dotnet restore

      - run:
          name: Build the application
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Publish the application
          command: dotnet publish --configuration Release --output ./publish --no-build

  docker_build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -f hello-world-api/Dockerfile -t $DOCKERHUB_USERNAME/helloworldapp:aditest hello-world-api

      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/helloworldapp:aditest

  sonarcloud_scan:
    docker:
      - image: circleci/openjdk:17-slim  # Choose an appropriate Docker image for SonarScanner
    steps:
      - checkout
      - run:
          name: Download SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip
            mv sonar-scanner-4.6.2.2472-linux sonar-scanner
      - run:
          name: Run SonarCloud Scan
          command: |
            ./sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=deathtkr_firsadit_repo \
              -Dsonar.organization=deathtkr \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - docker_build:
          requires:
            - sonarcloud_scan
      - sonarcloud_scan:
          requires:
            - build
