version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
  docker-executor:
    docker:
      - image: cimg/base:stable
  sonar-executor:
    docker:
      - image: openjdk:11-jdk-slim

jobs:
  build:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Clear nuget
          command: dotnet nuget locals all --clear
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build the application
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Publish the application
          command: dotnet publish --configuration Release --output ./publish --no-build

  sonarcloud_scan:
    executor: sonar-executor
    steps:
      - checkout
      - run:
          name: Install required tools
          command: |
            apt-get update && apt-get install -y unzip curl
      - run:
          name: Download SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip
            mv sonar-scanner-4.6.2.2472-linux sonar-scanner
      - run:
          name: Run SonarCloud Scan
          command: |
            ./sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=my-org_my-project \
              -Dsonar.organization=my-org \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
