apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      terminationGracePeriodSeconds: 30

      containers:
      - name: python-app
        image: aditya973/simplepythonwebsite:latest #gauris17/netflix:latest       
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000