apiVersion: apps/v1
kind: Deployment
metadata:
  name: adi-test
  labels:
    app: adi-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adi-test
  template:
    metadata:
      labels:
        app: adi-test
    spec:
      terminationGracePeriodSeconds: 30

      containers:
      - name: adi-test
        image: aditya973/helloworldapp:aditest #gauris17/netflix:latest       
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
