apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 32011
  selector:
    app: python-app
