apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-webapp
  endpoints:
  - port: http
    path: /metrics
