apiVersion: v1
kind: Service
metadata:
  name: adi-test
  labels:
    app: adi-test
spec:
  type: LoadBalancer
  loadBalancerIP: 51.8.78.152  # Specify the desired public IP address
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: adi-test
